import {db,one,many,ins,upd} from './db.js';
import {send,edit,answer} from './telegram.js';
import {TEAMS} from './teams.js';
import {makeFixtures} from './fixtures.js';
import {env,isAdmin} from './config.js';
import {esc,username,hoursLeft,parseScore} from './utils.js';

async function activeSeason(){return one('seasons',{status:'active'});}
async function userRow(u){let x=await one('users',{telegram_id:u.id});if(!x)x=await ins('users',{telegram_id:u.id,username:u.username||null,first_name:u.first_name||null,last_name:u.last_name||null});else await upd('users',{id:x.id},{username:u.username||x.username,first_name:u.first_name||x.first_name,last_name:u.last_name||x.last_name});return x;}
async function regFor(s,userId){return one('registrations',{season_id:s.id,user_id:userId});}
async function clubMap(){const rows=await many('clubs');return Object.fromEntries(rows.map(x=>[x.id,x]));}
async function openRound(s,roundNo){const round=await one('rounds',{season_id:s.id,round_no:roundNo});if(!round)throw Error('Round topilmadi');const until=new Date(Date.now()+86400000).toISOString();await upd('rounds',{id:round.id},{status:'open',opened_at:new Date().toISOString(),deadline_at:until,warning_sent:false});const regs=await many('registrations',{season_id:s.id});for(const r of regs){try{await send(r.telegram_id,`⚽ <b>${roundNo}-tur boshlandi!</b>\n⏰ 24 soat vaqt berildi.`)}catch{}}return round;}
async function standings(s){const clubs=await clubMap();const matches=await many('matches',{season_id:s.id});const rows={};for(const id of Object.keys(clubs))rows[id]={club_id:id,played:0,wins:0,draws:0,losses:0,gf:0,ga:0,gd:0,points:0};for(const m of matches){if(m.status!=='confirmed')continue;const a=rows[m.home_club_id],b=rows[m.away_club_id];a.played++;b.played++;a.gf+=m.home_goals;a.ga+=m.away_goals;b.gf+=m.away_goals;b.ga+=m.home_goals;if(m.home_goals>m.away_goals){a.wins++;b.losses++;a.points+=3}else if(m.home_goals<m.away_goals){b.wins++;a.losses++;b.points+=3}else{a.draws++;b.draws++;a.points++;b.points++}}return Object.values(rows).map(x=>({...x,gd:x.gf-x.ga,name:clubs[x.club_id]?.name||x.club_id})).sort((a,b)=>b.points-a.points||b.gd-a.gd||b.gf-a.gf);}
function tableText(rows){return rows.map((x,i)=>`${i+1}. <b>${esc(x.name)}</b> — ${x.played} O | ${x.wins} G | ${x.draws} D | ${x.losses} M | ${x.gf}:${x.ga} | ${x.gd>=0?'+':''}${x.gd} | <b>${x.points}</b>`).join('\n');}
async function matchesForUser(s,userId){const reg=await regFor(s,userId);if(!reg)return [];const ms=await many('matches',{season_id:s.id});return ms.filter(m=>m.home_user_id===userId||m.away_user_id===userId).sort((a,b)=>a.round_no-b.round_no);}
async function matchText(m,clubs,users){const h=clubs[m.home_club_id],a=clubs[m.away_club_id];const hu=users[m.home_user_id],au=users[m.away_user_id];return `⚽ <b>${m.round_no}-tur</b>\n🏠 ${esc(h.name)} — ${username(hu)}\n🆚\n🚩 ${esc(a.name)} — ${username(au)}\n⏰ ${m.deadline_at?hoursLeft(m.deadline_at)+' soat qoldi':''}\n📌 Holat: ${m.status==='confirmed'?`<b>${m.home_goals}:${m.away_goals}</b>`:m.status==='pending'?'Raqib tasdig‘i kutilmoqda':'Natija kiritilmagan'}`;}
export async function handleUpdate(update){
 if(update.callback_query)return callback(update.callback_query);
 if(!update.message)return;
 const m=update.message; const u=await userRow(m.from); const s=await activeSeason();
 if(m.text==='/start')return start(m,u,s);
 if(!s)return send(m.chat.id,'⏳ Hozir faol liga yo‘q.');
 const session=await one('sessions',{user_id:u.id});
 if(session?.type==='result'){const score=parseScore(m.text);if(!score)return send(m.chat.id,'Natijani <b>2-1</b> ko‘rinishida yuboring.');return submitResult(m,u,s,session.match_id,score);}
 if(session?.type==='chat'){if(m.text==='/chat_off'){await upd('sessions',{user_id:u.id},{type:null,match_id:null});return send(m.chat.id,'💬 Match chat yopildi.');}return relayChat(m,u,s,session.match_id);}
 if(m.text==='/admin'&&isAdmin(m.from.id))return adminMenu(m.chat.id);
 return send(m.chat.id,'Menyudan foydalaning.',mainKb());
}
async function start(m,u,s){if(!s)return send(m.chat.id,'👋 Salom! Liga hali boshlanmagan.');const r=await regFor(s,u.id);if(!r)return chooseClub(m.chat.id,s);return send(m.chat.id,`👋 Salom, <b>${esc(r.club_name||'klubingiz')}</b> vakili!`,mainKb());}
const mainKb=()=>({inline_keyboard:[[{'text':'🏆 Liga jadvali','callback_data':'table'},{'text':'⚽ Mening o‘yinim','callback_data':'mygame'}],[{'text':'📅 O‘yinlar jadvali','callback_data':'schedule'},{'text':'👤 Mening profilim','callback_data':'profile'}],[{'text':'📊 Statistika','callback_data':'stats'},{'text':'ℹ️ Liga haqida','callback_data':'info'}]]});
async function chooseClub(chat,s){const regs=await many('registrations',{season_id:s.id});const used=new Set(regs.map(r=>r.club_id));const clubs=await many('clubs');const available=clubs.filter(c=>!used.has(c.id));const kb=[];for(let i=0;i<available.length;i+=2)kb.push(available.slice(i,i+2).map(c=>({text:`⚽ ${c.name}`,callback_data:`club:${c.id}`})));return send(chat,'🏟 <b>Klubingizni tanlang:</b>\nBir ishtirokchi — bitta klub.',{reply_markup:{inline_keyboard:kb}});}
async function callback(cq){const u=await userRow(cq.from),s=await activeSeason();await answer(cq.id);if(!s)return send(cq.from.id,'⏳ Faol liga yo‘q.');const d=cq.data;
 if(d.startsWith('club:')){const clubId=d.slice(5);const old=await regFor(s,u.id);if(old)return send(cq.from.id,'Siz allaqachon klub tanlagansiz.');const taken=await one('registrations',{season_id:s.id,club_id:clubId});if(taken)return chooseClub(cq.from.id,s);const club=await one('clubs',{id:clubId});await ins('registrations',{season_id:s.id,user_id:u.id,club_id:clubId,telegram_id:cq.from.id,club_name:club.name});return send(cq.from.id,`✅ Siz <b>${esc(club.name)}</b> klubini tanladingiz.`,mainKb());}
 if(d==='table'){const rows=await standings(s);return send(cq.from.id,`🏆 <b>LIGA JADVALI</b>\n\n${tableText(rows)}`);}
 if(d==='mygame'){const ms=await matchesForUser(s,u.id);const m=ms.find(x=>x.round_status==='open'&&x.status!=='confirmed')||ms.find(x=>x.status!=='confirmed')||ms[0];if(!m)return send(cq.from.id,'O‘yin topilmadi.');const clubs=await clubMap();const users=Object.fromEntries((await many('users')).map(x=>[x.id,x]));return send(cq.from.id,await matchText(m,clubs,users),{reply_markup:{inline_keyboard:[[{text:'💬 Match chat',callback_data:`chat:${m.id}`},{text:'📝 Natijani kiritish',callback_data:`result:${m.id}`}]]}});}
 if(d==='schedule'){const ms=await many('matches',{season_id:s.id},{col:'round_no',asc:true});const clubs=await clubMap();let out='📅 <b>O‘YINLAR JADVALI</b>\n\n';for(let r=1;r<=38;r++){const x=ms.filter(m=>m.round_no===r);out+=`<b>${r}-tur</b>: ${x.map(m=>`${clubs[m.home_club_id].name}–${clubs[m.away_club_id].name}`).join(', ')}\n`;if(out.length>3800)break;}return send(cq.from.id,out);}
 if(d==='profile'){const r=await regFor(s,u.id);if(!r)return chooseClub(cq.from.id,s);const rows=await standings(s);const x=rows.find(z=>z.club_id===r.club_id);return send(cq.from.id,`👤 <b>Profil</b>\nKlub: <b>${esc(r.club_name)}</b>\nO‘yinlar: ${x.played}\nG‘alaba: ${x.wins}\nDurang: ${x.draws}\nMag‘lubiyat: ${x.losses}\nGF: ${x.gf}\nGA: ${x.ga}\nOchko: <b>${x.points}</b>`);}
 if(d==='stats')return stats(cq.from.id,s);
 if(d==='info')return send(cq.from.id,'ℹ️ <b>Premier League formati</b>\n20 klub • 38 tur • 380 o‘yin\nHar juftlik uy-safar 2 marta.\nG‘alaba 3, durang 1, mag‘lubiyat 0 ochko.\nHar tur 24 soat. 1 soat qolganda ogohlantirish. Vaqt tugasa tasdiqlanmagan natija 0:0.');
 if(d.startsWith('result:')){const mid=d.slice(7);const m=await one('matches',{id:mid});if(!m||m.home_user_id!==u.id&&m.away_user_id!==u.id)return send(cq.from.id,'Bu o‘yin sizniki emas.');await upd('sessions',{user_id:u.id},{type:'result',match_id:mid});return send(cq.from.id,'📝 Natijani <b>2-1</b> ko‘rinishida yuboring.');}
 if(d.startsWith('confirm:'))return confirmResult(cq.from.id,s,d.slice(8),u.id,true);
 if(d.startsWith('reject:'))return confirmResult(cq.from.id,s,d.slice(7),u.id,false);
 if(d.startsWith('chat:')){await upd('sessions',{user_id:u.id},{type:'chat',match_id:d.slice(5)});return send(cq.from.id,'💬 Match chatga kirdingiz. Xabaringizni yozing. Chiqish: /chat_off');}
 if(isAdmin(cq.from.id)&&d.startsWith('admin:'))return adminCallback(cq.from.id,s,d);
}
async function submitResult(m,u,s,mid,score){const match=await one('matches',{id:mid});if(!match)return send(m.chat.id,'O‘yin topilmadi.');if(match.home_user_id!==u.id&&match.away_user_id!==u.id)return send(m.chat.id,'Bu o‘yin sizniki emas.');if(match.round_status!=='open')return send(m.chat.id,'Bu tur hozir ochiq emas.');const hg=u.id===match.home_user_id?score.home:score.away,ag=u.id===match.home_user_id?score.away:score.home;await upd('matches',{id:mid},{home_goals:hg,away_goals:ag,status:'pending',submitted_by:u.id,submitted_at:new Date().toISOString()});await upd('sessions',{user_id:u.id},{type:null,match_id:null});const opp=u.id===match.home_user_id?match.away_user_id:match.home_user_id;return send(opp,`📝 Raqib <b>${esc(String(hg))}:${esc(String(ag))}</b> natija kiritdi. Tasdiqlaysizmi?`,{reply_markup:{inline_keyboard:[[{text:'✅ Confirm',callback_data:`confirm:${mid}`},{text:'❌ Reject',callback_data:`reject:${mid}`}]]}});}
async function confirmResult(chat,s,mid,userId,ok){const m=await one('matches',{id:mid});if(!m||m.status!=='pending')return send(chat,'Natija topilmadi yoki allaqachon ko‘rib chiqilgan.');const opp=m.submitted_by===m.home_user_id?m.away_user_id:m.home_user_id;if(userId!==opp)return send(chat,'Tasdiqlash faqat raqibga tegishli.');if(ok){await upd('matches',{id:mid},{status:'confirmed',confirmed_by:userId,confirmed_at:new Date().toISOString()});await send(m.submitted_by,'✅ Natija tasdiqlandi.');return send(chat,'✅ Natija rasmiy tasdiqlandi.');}await upd('matches',{id:mid},{status:'rejected',rejected_by:userId});for(const id of env.ADMIN_IDS)await send(id,`⚠️ <b>Natija rad etildi</b>\nMatch: ${mid}\nHisob: ${m.home_goals}:${m.away_goals}`);return send(chat,'❌ Rad etildi. Admin ko‘rib chiqadi.');}
async function relayChat(m,u,s,mid){const match=await one('matches',{id:mid});if(!match||match.home_user_id!==u.id&&match.away_user_id!==u.id)return send(m.chat.id,'Match chat topilmadi.');const opp=match.home_user_id===u.id?match.away_user_id:match.home_user_id;const text=`💬 <b>Match chat</b>\n${username(u)}: ${esc(m.text||'[media]')}`;await send(opp,text);for(const id of env.ADMIN_IDS)await send(id,text);return send(m.chat.id,'✓ Yuborildi');}
async function stats(chat,s){const clubs=await clubMap();const ms=await many('matches',{season_id:s.id});const confirmed=ms.filter(m=>m.status==='confirmed');const goals={};const wins={};const clean={};for(const m of confirmed){goals[m.home_club_id]=(goals[m.home_club_id]||0)+m.home_goals;goals[m.away_club_id]=(goals[m.away_club_id]||0)+m.away_goals;if(m.home_goals>m.away_goals)wins[m.home_club_id]=(wins[m.home_club_id]||0)+1;if(m.away_goals>m.home_goals)wins[m.away_club_id]=(wins[m.away_club_id]||0)+1;if(m.away_goals===0)clean[m.home_club_id]=(clean[m.home_club_id]||0)+1;if(m.home_goals===0)clean[m.away_club_id]=(clean[m.away_club_id]||0)+1;}const top=(obj)=>Object.entries(obj).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([id,v])=>`${esc(clubs[id]?.name||id)} — <b>${v}</b>`).join('\n')||'—';return send(chat,`📊 <b>STATISTIKA</b>\n\n⚽ Top goal-scoring clubs\n${top(goals)}\n\n🏆 Most wins\n${top(wins)}\n\n🧤 Clean sheets\n${top(clean)}`);}
async function adminMenu(chat){return send(chat,'🛠 <b>ADMIN PANEL</b>',{reply_markup:{inline_keyboard:[[{text:'▶️ Keyingi turni ochish',callback_data:'admin:open'}],[{text:'👥 Ishtirokchilar',callback_data:'admin:users'},{text:'⚠️ Rad etilganlar',callback_data:'admin:rejected'}],[{text:'🏁 Mavsumni tugatish',callback_data:'admin:finish'}]]}});}
async function adminCallback(chat,s,d){if(d==='admin:open'){const rs=await many('rounds',{season_id:s.id},{col:'round_no',asc:true});const next=rs.find(r=>r.status==='locked');if(!next)return send(chat,'Barcha turlar ochilgan.');await openRound(s,next.round_no);return send(chat,`▶️ ${next.round_no}-tur ochildi.`);}if(d==='admin:users'){const regs=await many('registrations',{season_id:s.id});return send(chat,'👥 <b>Ishtirokchilar</b>\n'+regs.map(r=>`${esc(r.club_name)} — ${esc(String(r.telegram_id))}`).join('\n'));}if(d==='admin:rejected'){const ms=(await many('matches',{season_id:s.id})).filter(m=>m.status==='rejected');return send(chat,'⚠️ <b>Rad etilgan natijalar</b>\n'+(ms.map(m=>`${m.id}: ${m.home_goals}:${m.away_goals}`).join('\n')||'Yo‘q'));}if(d==='admin:finish')return finishSeason(chat,s);}
async function finishSeason(chat,s){const rows=await standings(s);await upd('seasons',{id:s.id},{status:'finished',finished_at:new Date().toISOString(),champion_club_id:rows[0]?.club_id||null});let text=`🏁 <b>MAVSUM YAKUNLANDI</b>\n\n🥇 ${esc(rows[0]?.name||'—')}\n🥈 ${esc(rows[1]?.name||'—')}\n🥉 ${esc(rows[2]?.name||'—')}\n\n<b>Final jadval:</b>\n${tableText(rows)}`;for(const id of env.ADMIN_IDS)await send(id,text);return send(chat,text);}
export async function cron(){const s=await activeSeason();if(!s)return {ok:true};const rounds=await many('rounds',{season_id:s.id});const now=Date.now();for(const r of rounds){if(r.status!=='open'||!r.deadline_at)continue;const left=new Date(r.deadline_at).getTime()-now;const ms=await many('matches',{season_id:s.id,round_no:r.round_no});if(left<=3600000&&left>0&&!r.warning_sent){const regs=await many('registrations',{season_id:s.id});for(const reg of regs){const unfinished=ms.some(m=>(m.home_user_id===reg.user_id||m.away_user_id===reg.user_id)&&m.status!=='confirmed');if(unfinished)try{await send(reg.telegram_id,`⚠️ ${r.round_no}-tur deadline'iga 1 soat qoldi. Natijani kiriting!`)}catch{}}await upd('rounds',{id:r.id},{warning_sent:true});}if(left<=0){for(const m of ms.filter(x=>x.status!=='confirmed'))await upd('matches',{id:m.id},{status:'confirmed',home_goals:0,away_goals:0,confirmed_by:null,auto_result:true});await upd('rounds',{id:r.id},{status:'closed'});}}return {ok:true};}
